;;; (tein docs) — documentation accessors
;;;
;;; provides runtime access to module documentation alists
;;; generated by #[tein_module]. designed for LLM context dumps.

;; #t iff obj is a proper list whose every element is a pair
(define (alist? obj)
  (if (null? obj) #t
      (and (pair? obj) (pair? (car obj))
           (alist? (cdr obj)))))

(define (module-doc alist symbol)
  (let ((pair (assq symbol alist)))
    (and pair (cdr pair))))

(define (module-docs alist)
  (let loop ((rest alist) (acc '()))
    (cond
      ((null? rest) (reverse acc))
      ((eq? (caar rest) '__module__) (loop (cdr rest) acc))
      (else (loop (cdr rest) (cons (car rest) acc))))))

(define (describe alist)
  (if (not (alist? alist))
      (string-append
        "describe expects a docs alist (list of pairs), got: "
        (cond
          ((symbol? alist)
           (string-append "symbol '" (symbol->string alist)
             ". pass the alist directly, e.g. (describe harness-tools-docs)"))
          ((list? alist)
           "a flat list (not an alist). each element must be a (key . value) pair")
          (else "a non-list value")))
      (let ((mod (module-doc alist '__module__))
            (entries (module-docs alist)))
        (apply string-append
          (append
            (if mod (list "(" mod ")\n") '())
            (map (lambda (p)
                   (string-append
                     "  " (symbol->string (car p))
                     (if (string=? (cdr p) "")
                         "\n"
                         (string-append " — " (cdr p) "\n"))))
                 entries))))))
