;;; (tein docs) — documentation accessors
;;;
;;; provides runtime access to module documentation alists
;;; generated by #[tein_module]. designed for LLM context dumps.

(define (module-doc alist symbol)
  (let ((pair (assq symbol alist)))
    (and pair (cdr pair))))

(define (module-docs alist)
  (let loop ((rest alist) (acc '()))
    (cond
      ((null? rest) (reverse acc))
      ((eq? (caar rest) '__module__) (loop (cdr rest) acc))
      (else (loop (cdr rest) (cons (car rest) acc))))))

(define (describe alist)
  (if (not (pair? alist))
      (string-append
        "error: describe expects a docs alist (e.g. introspect-docs, harness-tools-docs), got: "
        (if (symbol? alist)
            (string-append "symbol '" (symbol->string alist)
              " — did you mean (describe " (symbol->string alist) "-docs)?")
            "a non-list value"))
      (let ((mod (module-doc alist '__module__))
            (entries (module-docs alist)))
        (apply string-append
          (append
            (if mod (list "(" mod ")\n") '())
            (map (lambda (p)
                   (string-append
                     "  " (symbol->string (car p))
                     (if (string=? (cdr p) "")
                         "\n"
                         (string-append " — " (cdr p) "\n"))))
                 entries))))))
